#!/bin/bash
# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0
# This file is to be `source`ed, so use `set -Eeuo pipefail` only inside functions

# __yyhelp_match
__yyhelp_match() # wildcard string matches
{
  case "$2" in
    $1) return 0 ;;					# Pattern $1 must be unquoted to allow *?[]
  esac
  return 1
}

# __yyhelp_echo_signoff
__yyhelp_echo_signoff()
(
  set -Eeuo pipefail #-x
  echo # separating newline before signoff section
  git var GIT_COMMITTER_IDENT | sed -e 's/>.*/>/ ; s/^/Signed-off-by: /'
)

# list_committable
__yyhelp_list_committable() # [FILES...]
(
  set -Eeuo pipefail #-x
  gitdir="$(git rev-parse --git-dir 2>/dev/null)"
  gitprefix="$(git rev-parse --show-prefix)" || : && test -z "$gitprefix" && gitprefix=. # no subdir support if GIT_DIR is set
  test -s "$gitdir/commit-ignore" && commitignore="$gitdir/commit-ignore" || commitignore=
  test -z "$*" && commitdir=. || commitdir=
  test "${BARE_PATHS:-}" = true && stripprefix="" || stripprefix="$gitprefix"
  test -n "$stripprefix" -a "${stripprefix: -1}" != / && stripprefix="$stripprefix/" # force trailing /
  TAB=$'\t'
  git diff-index --name-status --no-renames HEAD -- $commitdir "$@" | while IFS="$TAB" read -r mode file ; do
    case "$mode" in
      D)  test -n "$(git diff-files -- "$file")" && mode=! ;;
      M)  test -n "$commitignore" && fgrep -qx "$file" "$commitignore" && mode=n ;;
    esac
    if test "${BARE_PATHS:-}" = true ; then
      echo "${file#$stripprefix}"
    else
      echo -e "$mode\t${file#$stripprefix}"
    fi
  done
)

# commit_template
__yyhelp_commit_template() # [FILES...]
(
  set -Eeuo pipefail #-x
  BARE_PATHS=true __yyhelp_list_committable "$@" > "$gitdir/yycommit-template.lst"
  while read line ; do
    #f=$(printf %s "$line" | sed 's/\.[^\/.]*$//' ;) # file w/o extension
    f=$(printf %s "$line" ;)
    B="${f#*/}";	# strip root dir
    if test "$B" != "$f" ; then
      D="${f%%/*}";	# keep only root dir
      D="${D#.}";	# strip leading dot
      echo "${D^^*}: $B:" ;
    else
      echo "${f}: " ;
    fi
  done < "$gitdir/yycommit-template.lst"
  rm -f "$gitdir/yycommit-template.lst"
)

# __yyhelp_compgen_refs
__yyhelp_compgen_refs()
{ # $1=command $2=word4completion §3=precedingword
  local cur refs
  cur=${COMP_WORDS[COMP_CWORD]}
  COMPREPLY=()  # Array variable storing the possible completions.
  refs=$( git for-each-ref --format='%(refname:short)' refs/heads )
  #if test "$1" == "$3" ; then ... fi # completing first arg
  COMPREPLY=( $(compgen -W "$refs" -- "$cur") )
}

# __yyhelp_compgen_tags
__yyhelp_compgen_tags()
{
  local cur refs
  cur=${COMP_WORDS[COMP_CWORD]}
  COMPREPLY=()  # Array variable storing the possible completions.
  refs=$( git for-each-ref --format='%(refname:short)' refs/tags )
  if test "$1" == "$3" ; then # completing first arg
    COMPREPLY=( $(compgen -W "$refs" -- "$cur") )
  fi
}

# yytagdel
yytagdel()
(
  set -Eeuo pipefail
  while test x"${1:-}" != x ; do
    git tag -d "$1" || return $?
    shift
  done
)

# yycommit
yycommit()
(
  test "$1" == "${1#-p}" && PICK=false || { PICK=true; shift ; }
  test "$1" == "${1#-[0-9]}" && N=17 || { N=${1:1}; shift ; }
  set -Eeuo pipefail
  gitdir="$(git rev-parse --git-dir 2>/dev/null)"
  die() { echo "$*" 2>/dev/null ; exit -1 ; }
  $PICK && {
    __yyhelp_commit_template "$@" > "$gitdir/YYCOMMIT.txt"
    exec git commit -ps -t "$gitdir/YYCOMMIT.txt" "$@"
  }
  SUBDIRECTORY_OK=Yes
  TAB=$'\t'
  test true == `git rev-parse --is-inside-work-tree 2>/dev/null` || die "$0: Command requires a git working tree"
  verify_msg=true
  # parse and set AUTHOR and COMMITTER
  git var GIT_AUTHOR_IDENT    2>/dev/null | grep -q '\b[0-9]\{8,\}[ ]\+[+-][0-9]\+ *$' || die "$0: missing commit author information"
  git var GIT_COMMITTER_IDENT 2>/dev/null | grep -q '\b[0-9]\{8,\}[ ]\+[+-][0-9]\+ *$' || die "$0: missing committer information"
  AIDENT=$(git var GIT_AUTHOR_IDENT    | sed 's/\b\([0-9]\{8,\}[ ]\+[+-][0-9]\+ *\)$/\n\1/' | {
             read author; read time; echo -n "  $author" ; echo $time | gawk '{ print strftime (" %F %T %z", $1) }'
           })
  CIDENT=$(git var GIT_COMMITTER_IDENT | sed 's/\b\([0-9]\{8,\}[ ]\+[+-][0-9]\+ *\)$/\n\1/' | {
             read author; read time; echo -n "  $author" ; echo $time | gawk '{ print strftime (" %F %T %z", $1) }'
           })
  # update stat info for list_committable
  git update-index --refresh --verbose || :
  # construct commit message
  echo -n > "$gitdir/YYCOMMIT.txt" || exit $? # abort if not writable
  __yyhelp_commit_template "$@" > "$gitdir/YYCOMMIT.txt"
  YYCOMMIT_SIGNOFF=$(git config --get yycommit.signoff) || :
  if test "${YYCOMMIT_SIGNOFF:-true}" == true ; then
    __yyhelp_echo_signoff >> "$gitdir/YYCOMMIT.txt"
  fi
  echo >> "$gitdir/YYCOMMIT.txt"
  cat >> "$gitdir/YYCOMMIT.txt" <<-_EOF_HERE
	#YY: ----------------------------------------------------------------------
	#YY: Files to be committed (detected by "#YY:F"):
	#YY:
_EOF_HERE
  __yyhelp_list_committable "$@" | sed 's/^/#YY:F   /' >> "$gitdir/YYCOMMIT.txt"
  cat >> "$gitdir/YYCOMMIT.txt" <<-_EOF_HERE
	#YY:
	#YY: Author:
	#YY: $AIDENT
	#YY: Committer:
	#YY: $CIDENT
	#YY:
_EOF_HERE
  yyinfo | sed 's/^/#YY: /' >> "$gitdir/YYCOMMIT.txt"
  cat >> "$gitdir/YYCOMMIT.txt" <<-_EOF_HERE
	#YY:
	#YY: (The "#YY:" prefixed lines are ignored for commit messages)
_EOF_HERE
  GITHISTORY=$((git log --oneline HEAD ^HEAD~$N 2>/dev/null || :) | sed 's/^[^ ]*/#YY:/')
  test -z "$GITHISTORY" || {
    echo '#YY:'
    echo '#YY: Commit History:'
    echo "${GITHISTORY}"
  } >> "$gitdir/YYCOMMIT.txt"
  # edit commit message
  grep -q '^#YY:F ' "$gitdir/YYCOMMIT.txt" || { echo "** Nothing to commit." >&2 && exit 0 ; }
  ED=`git config --get core.editor` || :
  MD5USELESS=`grep -v -i '^#YY:' < "$gitdir/YYCOMMIT.txt" | git stripspace | md5sum`
  ${ED:-joe} "$gitdir/YYCOMMIT.txt" ||
    die "** Aborting commit, editing commit message failed: $gitdir/YYCOMMIT.txt"
  # verify user's commit message
  $verify_msg && test -x "$gitdir/hooks/commit-msg" && { "$gitdir/hooks/commit-msg" "$gitdir/YYCOMMIT.txt" || exit $? ; }
  mlines=`git stripspace < "$gitdir/YYCOMMIT.txt" | wc -l`
  md5now=`grep -v -i '^#YY:' < "$gitdir/YYCOMMIT.txt" | git stripspace | md5sum`
  test 0 -lt "$mlines" -a "$md5now" != "$MD5USELESS" || die "** Aborting commit, missing commit message..."
  # save current index around commit (since GIT_INDEX_FILE=tmpindex git-commit is buggy)
  TMPINDEX=`mktemp "$gitdir/.precommittindex$$.XXXXXX"` && cp -p "$gitdir/index" "$TMPINDEX" || die "$0: failed to create temporary file"
  trap 'mv -f "$TMPINDEX" "$gitdir/index"' 0 HUP INT QUIT TRAP USR1 PIPE TERM
  # unstage everything in index
  git read-tree HEAD
  # stage files from commit message
  grep "^#YY:F " "$gitdir/YYCOMMIT.txt" |             	# filter #YY:F
    sed -e "s/^#YY:F \+//" | {                          # extract file names
    while IFS=" $TAB" read -r mode file ; do
      case "$mode" in
        D)        git update-index --force-remove -- "$file" || die "** Aborting commit, removing failed: $file" ;;
        A|M)      git update-index --add          -- "$file" || die "** Aborting commit, adding failed: $file" ;;
        n)        ;; # commitignore
        '!')      ;; # missing file
        *)        die "** Aborting commit, unknown file mode: $mode $file" ;;
      esac
    done
  }
  sed '/^#YY:/d' -i "$gitdir/YYCOMMIT.txt"
  # abort for empty committs
  git diff-index --cached HEAD | grep -q '.' || { echo "** Nothing to commit." >&2 && exit 0 ; }
  # actually commit changes
  git commit -F "$gitdir/YYCOMMIT.txt" ; ccode=$?
  # cleanup, restore old index and force update on comitted files
  test 0 = $ccode && rm -f "$gitdir/YYCOMMIT.txt"
  mv -f "$TMPINDEX" "$gitdir/index"
  trap - 0 HUP INT QUIT TRAP USR1 PIPE TERM
  git update-index --refresh --again > /dev/null || : # update stat info
  sync &
  exit $ccode
)

# yydiff
yydiff()
(
  set -Eeuo pipefail #-x
  if __yyhelp_match '* -- *' " $* " ; then
    LESS="$LESS -+c" git diff HEAD "$@"
  elif __yyhelp_match '* -*' " $* " ; then
    LESS="$LESS -+c" git diff HEAD "$@" -- .
  else
    LESS="$LESS -+c" git diff HEAD -- "${@:-.}"
  fi
)

# yyinfo
yyinfo()
(
  set -Eeuo pipefail #-x
  gitdir="$(git rev-parse --git-dir 2>/dev/null)"
  GITURL="`git config --get remote.origin.url`" || :
  test -z "$GITURL" && GITURL="`cd \"$gitdir\" && pwd`" # no url, must be local
  REPO="`basename \"$(git rev-parse --show-toplevel)\" `"
  REPODIR="`git rev-parse --show-cdup`" || { test -z "$REPODIR" && REPODIR=. ; }
  test -z "$REPODIR" && CURRENT=. || CURRENT=`realpath --relative-to="$REPODIR" ./`
  HC="`git rev-parse --verify HEAD   2>/dev/null`"; test -n "$HC" && HC="`date -d \"$(git log -n1 --pretty=format:%cD $HC)\" '+%F %T %z'` # $HC"
  # origin/HEAD is not always present
  RH="`git rev-parse --verify origin 2>/dev/null`" || : ; test -n "$RH" && RH="`date -d \"$(git log -n1 --pretty=format:%cD $RH)\" '+%F %T %z'` # $RH"
  HSYM=$(git symbolic-ref HEAD || git rev-parse HEAD) && HSYM=${HSYM#refs/heads/}
  true			&& echo "GIT-Repo: $REPO"
  true			&& echo "URL:      $GITURL"
  true                  && echo "Path:     $CURRENT"
  true			|| echo "Method:   git-push and git-pull are used for updates"
  test -n "$HC"		&& echo "HEAD:     $HC"
  test -n "$HSYM"	&& echo "BRANCH:   $HSYM"
  test -n "$RH"		&& echo "Origin:   $RH"
  return 0
)

# yymerge
yymerge()
(
  source "$(git --exec-path)/git-sh-setup" # die, require_work_tree, etc
  if test "${1:-}" == '-m' ; then # merge into master
    if test "${2:-}" == '' ; then # merge current branch  into master
      BRANCH=$(git symbolic-ref HEAD) && BRANCH=${BRANCH#refs/heads/}
    else
      BRANCH="$2"
    fi
    git describe --dirty | fgrep -qe -dirty && die "$0: working tree must not be dirty"
    for MAIN in master main trunk ; do
      test -n "$(git config --get branch.$MAIN.remote)" && {
	yywarp $MAIN # master/trunk/main/etc
	break
      }
    done
    shift
  else
    BRANCH="$1"
  fi
  set -Eeuo pipefail				# fail early *after* git-sh-setup
  git var GIT_AUTHOR_IDENT    2>/dev/null | grep -q '\b[0-9]\{8,\}[ ]\+[+-][0-9]\+ *$' || die "$0: missing commit author information"
  git var GIT_COMMITTER_IDENT 2>/dev/null | grep -q '\b[0-9]\{8,\}[ ]\+[+-][0-9]\+ *$' || die "$0: missing committer information"
  git rev-parse -q --verify "$BRANCH^0" >/dev/null || die "$0: unknown revision: $BRANCH"
  gitdir="$(git rev-parse --git-dir 2>/dev/null)"
  test -e "$gitdir/MERGE_MSG" && die "$0: $gitdir/MERGE_MSG: another merge already in progress?"
  git --no-pager diff -U0 "HEAD..$BRANCH" |	# examine all branch changes
    egrep "^\+.*\b(XXX|WIP|FIXME)\b" &&		# work still to be done
    sleep 5
  SEP="^^^^^^^^^^^^^^^^^^^^^^^^^^"
  echo -e "$SEP MERGE-DRAFT $SEP # DELETE THIS" > "$gitdir/MERGE_MSG"
  echo -e "Merge branch '$BRANCH'\n\n* $BRANCH:" >> "$gitdir/MERGE_MSG"
  git log --pretty=$'\f%s%+b' "HEAD..$BRANCH" |
    sed '/^\(Signed-off-by\|Acked-by\|Tested-by\|Cc\):/d' |
    sed '/^$/d ; s/^/\t/ ; s/^\t\f/  /' >> "$gitdir/MERGE_MSG"
  YYCOMMIT_SIGNOFF=$(git config --get yycommit.signoff) || :
  if test "${YYCOMMIT_SIGNOFF:-true}" == true ; then
    __yyhelp_echo_signoff >> "$gitdir/MERGE_MSG"
  fi
  HO=`md5sum "$gitdir/MERGE_MSG"`
  $EDITOR "$gitdir/MERGE_MSG"
  HN=`md5sum "$gitdir/MERGE_MSG"`
  test "$HO" != "$HN" || {
    rm -f $gitdir/MERGE_MSG
    die "$0: aborting draft merge..."
  }
  git merge --no-edit --no-ff -m "`cat $gitdir/MERGE_MSG`" $BRANCH && rm -f $gitdir/MERGE_MSG
)

# yypushpull
yypushpull()
(
  set -Eeuo pipefail #-x
  git push "$@"
  git pull "$@"
)

# yystash
yystash()
(
  set -Eeuo pipefail #-x
  die() { echo "yystash: $*" 2>/dev/null ; exit -1 ; }
  test -n "${1:-}" || die "missing branch name"
  BRANCHNAME="$1"
  SYMBOLICHEAD=$(git symbolic-ref HEAD 2>/dev/null || git rev-parse HEAD)
  SYMBOLICHEAD=${SYMBOLICHEAD#refs/heads/}
  HLINE=$(git rev-list --oneline -n 1 HEAD --)
  git update-index -q --refresh # update unmerged and needs-updating state
  DIFFSTAT=$(git diff --stat --ignore-submodules HEAD --)
  test -z "$DIFFSTAT" && return # nothing to stash
  git show-ref -q --heads "stash-$BRANCHNAME" && die "Branch already exists: stash-$BRANCHNAME"
  TFILES=`mktemp -t yystash$$XXXXXX.tmp` && touch $TFILES || die "failed to create temporary file"
  trap "rm -f $TFILES" 0 HUP INT QUIT TRAP USR1 PIPE TERM
  # check working tree changes into index
  TREE_HASH=$(git diff --name-only -z HEAD -- > "$TFILES" \
                && git update-index -z --add --remove --stdin < "$TFILES" \
                && git write-tree) || die "failed to create tree object from index"
  COMMIT_HASH=$({ printf 'STASH: %s\n\n' "$BRANCHNAME" ; printf 'WIP on %s: %s\n%s' "$SYMBOLICHEAD" "$HLINE" "$DIFFSTAT" ; } \
                  | git commit-tree $TREE_HASH -p HEAD) || die "failed to commit tree $tree_hash"
  git branch "stash-$BRANCHNAME" $COMMIT_HASH || return $?
  git rev-list --pretty=oneline -n 1 "stash-$BRANCHNAME" --
  git checkout -f HEAD
)

# yystatus
yystatus()
(
  set -Eeuo pipefail #-x
  #__yyhelp_match '-[citu]' "$*" || { __yyhelp ; return ; }
  gitdir="$(git rev-parse --git-dir 2>/dev/null)"
  git update-index --refresh >/dev/null || :		# update stat info
  test -e $gitdir/info/exclude && EXCLUDE_FROM=--exclude-from=$gitdir/info/exclude || EXCLUDE_FROM=
  # list unknown files
  ! __yyhelp_match '*-[tc]*' "$*" &&
    git ls-files --others --directory $EXCLUDE_FROM --exclude-per-directory=.gitignore | {
      if test " $*" == " -u" ; then
	cat # sed '/\/$/d'
      elif test " $*" == " -i" ; then
	sed 's,^,/,; s,\(\.\),\\\1,g'			# abspath, escape .
      else
	sed $'s,^,?\t,'					# ?-prefix
      fi
    }
  # list known files
  __yyhelp_match '-[iu]' "$*" || {
    HEADREV=$(git rev-parse --verify $(git symbolic-ref -q HEAD 2>/dev/null) 2>/dev/null) || :
    if test -z "$HEADREV" ; then 			# empty history, list new files
      git ls-files | sed $'s/^/A\t/'
    else
      __yyhelp_list_committable				# list known files, path-relative
    fi
  } | {
    test " $*" != " -c" && cat ||
	sed 's/^[^ ]	\([^ ].*\)/* \1:/'
  }
)

# yyswitch
yyswitch()
{
  test ! -z "${__yyswitch_cmd}" ||
    git switch -h 2>/dev/null | grep -Fq branch &&
      __yyswitch_cmd=switch || __yyswitch_cmd=checkout
  git $__yyswitch_cmd "$@"
}

# yyview
yyview()
(
  git update-index --refresh
  gitk --all &
)

# yywarp
yywarp()
(
  test "$1" != "-" || exec git switch -
  test -z "$(git branch -l "$1")" || exec git switch "$1"
  git checkout "$@"
)

# yypurge
yypurge()
(
  set -Eeuo pipefail #-x
  gitdir="$(git rev-parse --git-dir 2>/dev/null)"
  git diff --src-prefix=HEAD --dst-prefix=worktree > "$gitdir/yypurge.tmpdiff"
  test -s "$gitdir/yypurge.tmpdiff" && mv "$gitdir/yypurge.tmpdiff" "$gitdir/yypurge.diff" || rm -f "$gitdir/yypurge.tmpdiff"
  git checkout -f HEAD
)

# yyhelp
__yyhelp()
(
  set -Eeuo pipefail #-x
  VERSION=YYHELP-22.07.25
  B='' ; N='' ; P=cat
  test -t 1 -a -t 0 && __yyhelp_match $'*\e[31m*' "`tput setaf 1 2>/dev/null`" && {
      B=$'\e[1m' ; N=$'\e[0m' ; P=${PAGER:-less}
    }
  #45678901234567890123456789012345678901234567890123456789012345678901234567890
  cat <<__EOF |
YYHELP                                                                    YYHELP

${B}NAME$N
	YYHELP - Simple and convenient Git wrapper

${B}SYNOPSIS$N
	yyadd [FILE]        Add file to the next commit, marks conflicts resolved
	yyblame [FILE]      Show revision and modifications per source code line
	yycommit [-[0-9] …] Use an editor to compose a commit and select files
	yydiff [--] [FILE]  Compare HEAD against working tree
	yyhelp              Show yyhelp command descriptions
	yyinfo              Show repository information
	yyll                One line log of all commits, with author and date
	yylr                One line log of all git refs
	yylog               Show git log with extra info
	yylp                Show diffs in git log
	yylsbranches        List branches
	yylstags            List tags
	yymerge [-m] <BRANCH> Merge BRANCH; -m: first warp to master/main/trunk
	yypull              Pull sources from upstream
	yypushpull [REMOTE] Push pending changes, else pull from upstream
	yypurge             Reset the worktree files to match a clean checkout
	                    (the last yypurge leaves changes in .git/yypurge.diff)
	yyrestore [FILE]    Restore a file from HEAD
	yyrestore [FILE]    Restore a file from HEAD
	yyrm [FILE]         Force remove file from working tree
	yystatus [-[citu]]  Display working tree status
	                    -c: commit style; -i: .gitignore style;
	                    -t: trim unknown; -u: show unknown;
	yystash <BRANCH>    Stash tree modifications into a branch
	yyswitch <BRANCH>   Switch to another branch
	yytagdel <TAG…>     Delete tags
	yyuncommit          Undo the last commit (must not be pushed)
	yyview              Run gitk(1) with all branches and tags in the background
	yywarp <COMMITISH>  Use yyswitch for branches or force checkout

${B}DESCRIPTION$N
	The yyhelp set of commands provide simple aliases around Git(7), that
	for the most part take only the working tree and existing refs into
	account.
	The scope of this wrapper is confined to a fairly basic set of actions
	around source control management, such as adding, removing. modifying
	files and the simplest forms of tag and branch handling.

${B}INSTALLATION$N
	To install yyhelp, copy yyhelp into the ~/bin/ directory and invoke
		source yyhelp --aliases

${B}HISTORY$N
	Yyhelp was originally created (named YummyYummySourceControl) as a very
	shallow porcelain script around Git(7) tool option variants, to simplify
	common use cases, especially after cogito vanished.
	The prefix 'yy' was chosen to allow fast, conflict free shell completion.

$VERSION                                                           YYHELP
__EOF
  LESS="$LESS -+F -c" $P
  #	yylg                One line log of simplified history
)

# alias installation
__yyhelp_aliases()
{
  alias yyadd='git add'
  alias yyblame='LESS="$LESS -F" git blame'
  #alias yylg='git log --graph --decorate --oneline'
  alias yylr='LESS="$LESS -F" git log --graph --decorate --oneline --simplify-by-decoration --all'
  alias yyll='LESS="$LESS -F" git log --graph --decorate --full-history --all --pretty="%C(yellow)%h%Creset%C(auto)%d%Creset %s %C(bold blue)<%aL>%Creset %C(white dim)%cs%Creset"'
  alias yylog='LESS="$LESS -F" git log --stat'
  alias yylp='LESS="$LESS -F" git log -p --stat'
  alias yypull='git pull'
  alias yyrestore='git restore --source HEAD'
  alias yyrm='git rm --force'
  alias yyuncommit='git reset --mixed -N HEAD~1'
  alias yylsbranches='LESS="$LESS -F" git branch -a -vv'
  alias yylstags='LESS="$LESS -F" git tag -n1 -l \*'
  # completions
  test -s /usr/share/bash-completion/completions/git || return
  source /usr/share/bash-completion/completions/git
  __git_complete yyadd _git_add
  #__git_complete yyblame _git_blame
  __git_complete yydiff _git_diff
  complete -W "--aliases" yyhelp
  #__git_complete yylg _git_log
  __git_complete yylr _git_log
  __git_complete yyll _git_log
  __git_complete yylog _git_log
  __git_complete yylp _git_log
  __git_complete yypull _git_pull
  __git_complete yypushpull __git_complete_remote_or_refspec
  complete -F __yyhelp_compgen_refs yymerge
  __git_complete yyrestore _git_restore
  __git_complete yyrm _git_rm
  complete -W '-c -i -t -u' yystatus
  __git_complete yystash __git_complete_refs
  complete -F __yyhelp_compgen_tags yytagdel
  complete -F __yyhelp_compgen_refs yymerge
  if [[ $(type -t _git_switch) == function ]] ; then
    __git_complete yyswitch _git_switch
  else
    __git_complete yyswitch _git_checkout
  fi
  __git_complete yywarp _git_checkout
}

# handle arguments
test $# -ne 0 || __yyhelp
while test $# -ne 0 ; do
  case "$1" in
    --aliases)	shift ; __yyhelp_aliases ;;
    *)		shift ;;
  esac
done

true
